"""
gwf/models/film.py
==================
Module 7: FiLM Prediction Layer

Uses the spatially-varying Beta coefficients (from HyperNet) to modulate
the tabular features (from the TabPFN bridge), producing the final
prediction-ready representation.

Traditional GWR: y_i = Σ_k beta_k(s_i) * x_ik   (scalar * scalar)
GWF:             h_pred_i = LayerNorm(gamma_i ⊙ h_x_i + delta_i)   (high-dim)

gamma and delta are derived by applying Beta_i (low-rank matrix) to h_x_i.
The low-rank matrix multiply avoids forming the full d×d matrix.

Architecture:
  Step 1: h_x = MLP_out(h_tabfpn)
            extra MLP gives tabular features a final transformation
  Step 2: Apply Beta via low-rank matrix multiply (efficient)
            Vh      = V_i @ h_x_i            (r,)
            sVh     = sigma_i * Vh            (r,)
            beta_h  = U_i @ sVh              (d,)
  Step 3: FiLM modulation
            gamma   = Linear(d, d)(beta_h)
            delta   = Linear(d, d)(beta_h)
            h_pred  = LayerNorm(gamma * h_x + delta)
"""

import torch
import torch.nn as nn


class FiLMLayer(nn.Module):
    """
    FiLM (Feature-wise Linear Modulation) prediction layer.

    Modulates tabular features h_tabfpn with spatially-varying Beta
    coefficients generated by the HyperNet.

    Args:
        d : embedding dimension (default 512)
    """

    def __init__(self, d: int = 512):
        super().__init__()
        self.d = d

        # Step 1: Extra MLP transforms tabular features before modulation
        self.mlp_out = nn.Sequential(
            nn.Linear(d, d),
            nn.GELU(),
            nn.LayerNorm(d),
            nn.Linear(d, d),
        )

        # Step 3: Project beta_h to scale (gamma) and shift (delta)
        self.gamma_proj = nn.Linear(d, d)
        self.delta_proj = nn.Linear(d, d)

        self.norm = nn.LayerNorm(d)

    def forward(
        self,
        h_tabfpn: torch.Tensor,          # (N, d)
        beta:     dict[str, torch.Tensor],  # {"U":(N,d,r), "sigma":(N,r), "V":(N,r,d)}
    ) -> torch.Tensor:
        """
        Returns h_pred (N, d).
        """
        U     = beta["U"]     # (N, d, r)
        sigma = beta["sigma"]  # (N, r)
        V     = beta["V"]     # (N, r, d)

        # ---- Step 1: Transform tabular features ----
        h_x = self.mlp_out(h_tabfpn)          # (N, d)

        # ---- Step 2: Low-rank matrix multiply (Beta_i @ h_x_i) ----
        # Vh    = V_i @ h_x_i : (N, r, d) @ (N, d, 1) → (N, r, 1) → (N, r)
        Vh    = torch.bmm(V, h_x.unsqueeze(-1)).squeeze(-1)    # (N, r)
        # sVh   = diag(sigma_i) @ Vh : element-wise (N, r)
        sVh   = sigma * Vh                                      # (N, r)
        # beta_h = U_i @ sVh : (N, d, r) @ (N, r, 1) → (N, d, 1) → (N, d)
        beta_h = torch.bmm(U, sVh.unsqueeze(-1)).squeeze(-1)   # (N, d)

        # ---- Step 3: FiLM modulation ----
        gamma  = self.gamma_proj(beta_h)                        # (N, d)
        delta  = self.delta_proj(beta_h)                        # (N, d)
        h_pred = self.norm(gamma * h_x + delta)                 # (N, d)

        return h_pred
