"""
GWF — Differentiable Matrix-Form WLS in TabPFN Embedding Space

Inspired by GNNWR (Du et al., IJGIS 2020), we retain the analytical WLS
formulation but operate in the TabPFN hidden-feature space instead of the
raw tabular feature space.

For each query location i with k neighbours, the regression is:

    Z̃_N  =  z_N @ K_z                          (project TabPFN embeddings)
    β_i  =  (Z̃_N^T diag(w_i) Z̃_N + λI)^{-1}  Z̃_N^T diag(w_i) y_N

where:
  • z_N  ∈ R^{k × tabpfn_dim}  — TabPFN pre-MLP hidden states of neighbours
  • K_z  ∈ R^{tabpfn_dim × z_proj_dim}  — location-adaptive low-rank projection
                                            (generated by DynamicKernelGenerator)
  • w_i  ∈ R^{k}               — learned spatial attention weights (GNNWR-style)
  • λ                           — ridge regularisation

β_i ∈ R^{z_proj_dim} — local coefficient vector in the projected embedding space.
Still spatially varying; can be visualised via t-SNE or PCA.

Prediction at query point i:
    ŷ_i  =  (z_query @ K_z) · β_i
"""

import torch
import torch.nn as nn


class MatrixGWR(nn.Module):
    """
    Closed-form, differentiable WLS in the K_z-projected TabPFN embedding space.
    No trainable parameters here — all parameters live in DynamicKernelGenerator.
    """

    def __init__(self, lam: float = 1e-3):
        super().__init__()
        self.lam = lam

    def forward(self,
                z_query: torch.Tensor,
                K_z:     torch.Tensor,
                z_nbr:   torch.Tensor,
                y_nbr:   torch.Tensor,
                w:       torch.Tensor
                ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Parameters
        ----------
        z_query : (B, tabpfn_dim)     — TabPFN hidden state of query points
        K_z     : (B, tabpfn_dim, e)  — location-adaptive projection, e = z_proj_dim
        z_nbr   : (B, k, tabpfn_dim)  — TabPFN hidden states of neighbours
        y_nbr   : (B, k)              — neighbour targets
        w       : (B, k)              — attention weights (sum ≈ 1)

        Returns
        -------
        y_hat : (B,)              — predictions
        beta  : (B, z_proj_dim)   — local coefficients in projected space
        """
        B, k, d = z_nbr.shape    # d = tabpfn_dim
        e = K_z.shape[-1]        # e = z_proj_dim

        # ── 1. Project z into regression subspace: Z̃ = z @ K_z ───────────
        # z_query: (B, d) → (B, 1, d) @ (B, d, e) → (B, 1, e) → (B, e)
        z_q_tilde = torch.bmm(z_query.unsqueeze(1), K_z).squeeze(1)     # (B, e)
        # z_nbr:   (B, k, d) @ (B, d, e) → (B, k, e)
        Z_tilde   = torch.bmm(z_nbr, K_z)                                # (B, k, e)

        # ── 2. Weighted normal equations ───────────────────────────────────
        # W = diag(w)  so  Z̃^T W Z̃ = Σ_j w_j · z̃_j z̃_j^T
        w_sqrt = w.sqrt().unsqueeze(-1)          # (B, k, 1)
        Zw     = Z_tilde * w_sqrt                # (B, k, e)  ← Z̃ ⊙ √w (per row)

        # Z̃^T W Z̃ = Zw^T Zw
        A = torch.bmm(Zw.transpose(1, 2), Zw)   # (B, e, e)

        # Ridge: A + λI
        eye = torch.eye(e, device=A.device, dtype=A.dtype).unsqueeze(0)
        A   = A + self.lam * eye                 # (B, e, e)

        # Z̃^T W y = Σ_j w_j · z̃_j · y_j
        wy = (w * y_nbr).unsqueeze(-1)           # (B, k, 1)
        b  = torch.bmm(Z_tilde.transpose(1, 2), wy).squeeze(-1)  # (B, e)

        # ── 3. Solve: β_i = A^{-1} b ──────────────────────────────────────
        beta = torch.linalg.solve(A, b)          # (B, e)

        # ── 4. Predict: ŷ_i = (z_query @ K_z) · β_i ─────────────────────
        y_hat = (z_q_tilde * beta).sum(dim=-1)   # (B,)

        return y_hat, beta
